# Generated by Django 3.2.6 on 2021-08-09 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('PS3', 'PlayStation 3'), ('PS4', 'PlayStation 4'), ('PS5', 'PlayStation 5'), ('XBOX', 'Xbox gaming')], default='PS3', max_length=5)),
                ('device_name', models.CharField(max_length=100)),
                ('price_hour', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamer_status', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=9)),
                ('gamer_name', models.CharField(max_length=100)),
                ('gamer_birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RentedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField()),
                ('gamer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.gamer')),
                ('rented_device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.device')),
            ],
        ),
    ]
